version: "3.7"

services:
  db:
    image: postgres
    restart: always
    container_name: nest-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
    volumes:
      - ./appdata/server/postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"